name: Commit Message Check

on: [push]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli husky

      - name: Run CommitLint
        run: npx commitlint --from=HEAD~1 --to=HEAD --config @commitlint/config-conventional
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
